version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5521:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresCenterpart
      POSTGRES_PASSWORD: vCi2LgsNQ9XFzngqh8u
      POSTGRES_DB: centerparts
    restart: unless-stopped

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    container_name: nodejs-container
    ports:
      - "9000:3000"
    volumes:
      - ./tmp/uploads:/app/tmp/uploads
    depends_on:
      - postgres
    restart: unless-stopped
