version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3399:3306"
    environment:
      MYSQL_DATABASE: centerparts
      MYSQL_USER: centerparts-user
      MYSQL_PASSWORD: regnoS@ndR@Msuad02
      MYSQL_ROOT_PASSWORD: regnoSuPe4r00tP4@ss
    volumes:
      - ./mysql-data:/var/lib/mysql
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    container_name: nodejs-container
    ports:
      - "9000:3000"
    volumes:
      - ./tmp/uploads:/app/tmp/uploads
    depends_on:
      - mysql
    restart: unless-stopped