version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: centerparts

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    container_name: nodejs-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  postgres-data:
